name: Matrix Calculator CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake doxygen graphviz libgtest-dev googletest

    - name: Build GTest
      run: |
        cd /usr/src/googletest
        sudo mkdir build && cd build
        sudo cmake ..
        sudo make
        sudo make install

    - name: Build application with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./matrix_calculator  # или имя вашего тестового приложения

    - name: Generate documentation
      run: doxygen Doxyfile

    - name: Check memory leaks
      run: |
        sudo apt-get install -y valgrind
        cd build
        valgrind --leak-check=full ./matrix_calculator
